version: '2'

services:

  php-apache:
    image: asprega/php-apache-symfony:0.1.0
    ports:
      - '80:80'
    volumes:
      - ./sf-app:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
